### ISSUE TITLE
Colors of some GTK4/LibAdwaita elements are incorrect

### ISSUE THREAD

**Issue by Inderix** [FrancescoCaracciolo/material-you-colors#7]
Specific elements appear wonky with the color changes the extension applies:

- Sidebars when not focused appear unchanged from the default colors of GTK. The sidebar is colored correctly when focused however.
Pictured here: Mission Center (unfocused) and Alpaca (focused). 
![image](https://github.com/user-attachments/assets/360f4b40-8c47-486d-b14b-3baa43d625ca)
- The background "tint" for dialogs within applications is a solid color, obstructing the content behind the dialog.
Pictured: The "Manage Models" dialog in the Alpaca app, the content behind the dialog is obstructed by the solid gray background that should be transparent. 
![image](https://github.com/user-attachments/assets/2131cacd-a50c-4ee8-ad07-3d346cdecd32)

**Comment by FrancescoCaracciolo** [comment]
Thanks for the issue, I will try to fix it

**Comment by FrancescoCaracciolo** [comment]
Fixed in 875d0eaf82c4751e1b3e7c105d6b3caedb982ab5
